import { describe, expect, it } from "vitest";
import { buildDashboardKpiMetrics, buildDashboardKpiSparks } from "./kpi-sparks";

describe("buildDashboardKpiSparks", () => {
  it("agrège les 6 derniers snapshots en séries réelles pour les KPI du dashboard", () => {
    const sparks = buildDashboardKpiSparks(
      [
        {
          snapshot_date: "2026-04-10",
          campaign_id: "camp-1",
          campaign_status: "active",
          leads_raw: 10,
          leads_qualified: 4,
          emails_sent: 10,
          opens: 3,
          clicks: 0,
          replies: 0,
          meetings: 0,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-11",
          campaign_id: "camp-1",
          campaign_status: "active",
          leads_raw: 12,
          leads_qualified: 5,
          emails_sent: 12,
          opens: 4,
          clicks: 0,
          replies: 0,
          meetings: 1,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-11",
          campaign_id: "camp-2",
          campaign_status: "generating",
          leads_raw: 9,
          leads_qualified: 3,
          emails_sent: 8,
          opens: 2,
          clicks: 0,
          replies: 0,
          meetings: 0,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-12",
          campaign_id: "camp-1",
          campaign_status: "active",
          leads_raw: 12,
          leads_qualified: 7,
          emails_sent: 16,
          opens: 7,
          clicks: 0,
          replies: 0,
          meetings: 1,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-12",
          campaign_id: "camp-2",
          campaign_status: "active",
          leads_raw: 10,
          leads_qualified: 6,
          emails_sent: 10,
          opens: 3,
          clicks: 0,
          replies: 0,
          meetings: 1,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-13",
          campaign_id: "camp-1",
          campaign_status: "paused",
          leads_raw: 12,
          leads_qualified: 8,
          emails_sent: 18,
          opens: 8,
          clicks: 0,
          replies: 0,
          meetings: 1,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-13",
          campaign_id: "camp-2",
          campaign_status: "active",
          leads_raw: 10,
          leads_qualified: 7,
          emails_sent: 14,
          opens: 5,
          clicks: 0,
          replies: 0,
          meetings: 1,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-14",
          campaign_id: "camp-2",
          campaign_status: "active",
          leads_raw: 10,
          leads_qualified: 9,
          emails_sent: 16,
          opens: 7,
          clicks: 0,
          replies: 0,
          meetings: 2,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-15",
          campaign_id: "camp-2",
          campaign_status: "active",
          leads_raw: 10,
          leads_qualified: 10,
          emails_sent: 18,
          opens: 8,
          clicks: 0,
          replies: 0,
          meetings: 3,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-16",
          campaign_id: "camp-2",
          campaign_status: "active",
          leads_raw: 10,
          leads_qualified: 12,
          emails_sent: 20,
          opens: 10,
          clicks: 0,
          replies: 0,
          meetings: 4,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
      ],
      6
    );

    expect(sparks.activeCampaigns).toEqual([2, 2, 1, 1, 1, 1]);
    expect(sparks.qualifiedLeads).toEqual([8, 13, 15, 9, 10, 12]);
    expect(sparks.openRate).toEqual([30, 38.5, 40.6, 43.8, 44.4, 50]);
    expect(sparks.meetingsBooked).toEqual([1, 2, 2, 2, 3, 4]);
  });

  it("retourne des séries vides quand aucun snapshot n'est disponible", () => {
    expect(buildDashboardKpiSparks([])).toEqual({
      activeCampaigns: [],
      qualifiedLeads: [],
      openRate: [],
      meetingsBooked: [],
    });
  });
});

describe("buildDashboardKpiMetrics", () => {
  it("calcule les deltas a partir des deux derniers snapshots disponibles", () => {
    const metrics = buildDashboardKpiMetrics(
      [
        {
          snapshot_date: "2026-04-11",
          campaign_id: "camp-1",
          campaign_status: "active",
          leads_raw: 12,
          leads_qualified: 5,
          emails_sent: 12,
          opens: 4,
          clicks: 0,
          replies: 0,
          meetings: 1,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-11",
          campaign_id: "camp-2",
          campaign_status: "active",
          leads_raw: 10,
          leads_qualified: 6,
          emails_sent: 10,
          opens: 3,
          clicks: 0,
          replies: 0,
          meetings: 1,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-12",
          campaign_id: "camp-1",
          campaign_status: "active",
          leads_raw: 12,
          leads_qualified: 7,
          emails_sent: 16,
          opens: 7,
          clicks: 0,
          replies: 0,
          meetings: 1,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
        {
          snapshot_date: "2026-04-12",
          campaign_id: "camp-2",
          campaign_status: "paused",
          leads_raw: 10,
          leads_qualified: 4,
          emails_sent: 8,
          opens: 2,
          clicks: 0,
          replies: 0,
          meetings: 0,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
      ],
      6
    );

    expect(metrics.deltas).toEqual({
      activeCampaigns: -1,
      qualifiedLeads: 0,
      openRate: 5.7,
      meetingsBooked: -1,
    });
  });

  it("retourne des deltas nuls quand il n'y a pas assez d'historique", () => {
    expect(
      buildDashboardKpiMetrics([
        {
          snapshot_date: "2026-04-12",
          campaign_id: "camp-1",
          campaign_status: "active",
          leads_raw: 12,
          leads_qualified: 7,
          emails_sent: 16,
          opens: 7,
          clicks: 0,
          replies: 0,
          meetings: 1,
          reply_rate: 0,
          booking_rate: 0,
          top_template: "",
          metadata: "",
        },
      ]).deltas
    ).toEqual({
      activeCampaigns: 0,
      qualifiedLeads: 0,
      openRate: 0,
      meetingsBooked: 0,
    });
  });
});
